// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBouI98JPkOzDvmGro4pKAdoDg7a8V0Kds',
    appId: '1:1000204221269:web:9d8c824e3e8cb0da750ddc',
    messagingSenderId: '1000204221269',
    projectId: 'blocbase-83d49',
    authDomain: 'blocbase-83d49.firebaseapp.com',
    storageBucket: 'blocbase-83d49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVK1XRUCB-mAAqSRQNoDAzgLr65Kjs8YU',
    appId: '1:1000204221269:android:2cf619055bea5bf5750ddc',
    messagingSenderId: '1000204221269',
    projectId: 'blocbase-83d49',
    storageBucket: 'blocbase-83d49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSSS_CgO2-p9SQ9eIxO2tZPVPB8x0Pwgs',
    appId: '1:1000204221269:ios:06dc27208e50d0e6750ddc',
    messagingSenderId: '1000204221269',
    projectId: 'blocbase-83d49',
    storageBucket: 'blocbase-83d49.appspot.com',
    iosClientId: '1000204221269-3975sliom0qapt1tc3tq57bn35jmne1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.bigwallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSSS_CgO2-p9SQ9eIxO2tZPVPB8x0Pwgs',
    appId: '1:1000204221269:ios:59437c01ee13b806750ddc',
    messagingSenderId: '1000204221269',
    projectId: 'blocbase-83d49',
    storageBucket: 'blocbase-83d49.appspot.com',
    iosClientId: '1000204221269-ddm2s118ji6lbkl6nve81a91f26k7h4k.apps.googleusercontent.com',
    iosBundleId: 'com.sota.blocBase',
  );
}
